# cmake/SwageBuildIdentity.cmake
# Records what a native build was made from, in two forms that one run of
# this file writes together: the header the Python extension compiles in,
# and the `_build_info.json` file packaged beside it.
#
# The build runs this file in script mode before it compiles the Python
# extension, on every build, so the record follows the checkout instead of
# the last configure. Each output is rewritten only when its content
# changes, so an unchanged checkout recompiles nothing.
#
#   cmake -DSWAGE_SOURCE_DIR=<checkout> -DSWAGE_IDENTITY_HEADER=<header> \
#     -DSWAGE_BUILD_INFO=<json> -DSWAGE_LLVM_TAG=<tag> \
#     -DSWAGE_BUILD_TYPE=<type> -P cmake/SwageBuildIdentity.cmake
#
# The header records the `swage` version in python/swage/__init__.py, the
# source revision, and the frontend digest. The revision is the full commit
# hash, followed by `-dirty` when a tracked file differs from that commit,
# or `unknown` when the sources are not a git checkout or git cannot
# describe them.
#
# The JSON file (schema 2) records the same facts in separate fields: the
# 40-digit revision or null, whether the tracked files matched it, the
# frontend digest, the LLVM pin, and the build type. A build from sources
# without git, such as a wheel built from an sdist, passes
# SWAGE_SOURCE_REVISION and SWAGE_SOURCE_CLEAN instead.
#
# The frontend digest is computed once and written to both records: the
# SHA-256 of one line per Python source of python/swage, sorted by relative
# path, each `<path> <SHA-256 of the file>` and a newline. Files and
# directories whose name starts with a dot, dangling symbolic links, and
# directories named like a module are left out. `swage._runtime` computes
# the same digest of the package it loads (`_frontend_digest`), pairs the
# bindings with it, and refuses to write an artifact when they differ.

set(SWAGE_VERSION_FILE "${SWAGE_SOURCE_DIR}/python/swage/__init__.py")
file(STRINGS "${SWAGE_VERSION_FILE}" SWAGE_VERSION_LINE
  REGEX "^__version__ = \"[^\"]+\"$")
string(REGEX REPLACE "^__version__ = \"([^\"]+)\"$" "\\1"
  SWAGE_BUILD_VERSION "${SWAGE_VERSION_LINE}")
if(NOT SWAGE_BUILD_VERSION)
  message(FATAL_ERROR
    "${SWAGE_VERSION_FILE} has no line of the form __version__ = \"X\", "
    "which names the swage version the bindings are built for.")
endif()

set(SWAGE_BUILD_REVISION "unknown")
set(SWAGE_INFO_REVISION "null")
set(SWAGE_INFO_CLEAN "false")
find_package(Git QUIET)
if(DEFINED SWAGE_SOURCE_REVISION AND NOT SWAGE_SOURCE_REVISION STREQUAL "")
  set(SWAGE_BUILD_REVISION "${SWAGE_SOURCE_REVISION}")
  set(SWAGE_INFO_REVISION "\"${SWAGE_SOURCE_REVISION}\"")
  if(SWAGE_SOURCE_CLEAN STREQUAL "true")
    set(SWAGE_INFO_CLEAN "true")
  else()
    string(APPEND SWAGE_BUILD_REVISION "-dirty")
  endif()
elseif(GIT_FOUND AND EXISTS "${SWAGE_SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${SWAGE_SOURCE_DIR}"
    OUTPUT_VARIABLE SWAGE_HEAD
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE SWAGE_HEAD_RESULT)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${SWAGE_SOURCE_DIR}"
    OUTPUT_VARIABLE SWAGE_CHANGES
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE SWAGE_CHANGES_RESULT)
  if(SWAGE_HEAD_RESULT EQUAL 0 AND SWAGE_CHANGES_RESULT EQUAL 0
     AND SWAGE_HEAD MATCHES "^[0-9a-f]+$")
    set(SWAGE_BUILD_REVISION "${SWAGE_HEAD}")
    set(SWAGE_INFO_REVISION "\"${SWAGE_HEAD}\"")
    if(NOT SWAGE_CHANGES STREQUAL "")
      string(APPEND SWAGE_BUILD_REVISION "-dirty")
    else()
      set(SWAGE_INFO_CLEAN "true")
    endif()
  endif()
endif()

set(SWAGE_FRONTEND_ROOT "${SWAGE_SOURCE_DIR}/python/swage")
file(GLOB_RECURSE SWAGE_FRONTEND_SOURCES
  RELATIVE "${SWAGE_FRONTEND_ROOT}" "${SWAGE_FRONTEND_ROOT}/*.py")
list(SORT SWAGE_FRONTEND_SOURCES)
set(SWAGE_FRONTEND_LINES "")
foreach(SWAGE_SOURCE IN LISTS SWAGE_FRONTEND_SOURCES)
  if(SWAGE_SOURCE MATCHES "(^|/)\\." OR
     NOT EXISTS "${SWAGE_FRONTEND_ROOT}/${SWAGE_SOURCE}" OR
     IS_DIRECTORY "${SWAGE_FRONTEND_ROOT}/${SWAGE_SOURCE}")
    continue()
  endif()
  file(SHA256 "${SWAGE_FRONTEND_ROOT}/${SWAGE_SOURCE}" SWAGE_SOURCE_DIGEST)
  string(APPEND SWAGE_FRONTEND_LINES "${SWAGE_SOURCE} ${SWAGE_SOURCE_DIGEST}\n")
endforeach()
string(SHA256 SWAGE_FRONTEND_DIGEST "${SWAGE_FRONTEND_LINES}")

set(SWAGE_IDENTITY_TEXT
"// Generated by cmake/SwageBuildIdentity.cmake on every build. Do not edit.
#ifndef SWAGE_PYTHON_BUILDIDENTITY_H
#define SWAGE_PYTHON_BUILDIDENTITY_H

#define SWAGE_BUILD_VERSION \"${SWAGE_BUILD_VERSION}\"
#define SWAGE_BUILD_REVISION \"${SWAGE_BUILD_REVISION}\"
#define SWAGE_BUILD_FRONTEND \"${SWAGE_FRONTEND_DIGEST}\"

#endif // SWAGE_PYTHON_BUILDIDENTITY_H
")

set(SWAGE_IDENTITY_PREVIOUS "")
if(EXISTS "${SWAGE_IDENTITY_HEADER}")
  file(READ "${SWAGE_IDENTITY_HEADER}" SWAGE_IDENTITY_PREVIOUS)
endif()
if(NOT SWAGE_IDENTITY_PREVIOUS STREQUAL SWAGE_IDENTITY_TEXT)
  file(WRITE "${SWAGE_IDENTITY_HEADER}" "${SWAGE_IDENTITY_TEXT}")
endif()

if(DEFINED SWAGE_BUILD_INFO)
  configure_file("${SWAGE_SOURCE_DIR}/python/mlir_swage/_build_info.json.in"
    "${SWAGE_BUILD_INFO}" @ONLY)
endif()
