# cmake/SwageBuildIdentity.cmake
# Writes the header that records what a native build was made from: the
# `swage` version in python/swage/__init__.py and the source revision.
#
# The build runs this file in script mode before it compiles the Python
# extension, on every build, so the record follows the checkout instead of
# the last configure. The header is rewritten only when its content changes,
# so an unchanged checkout recompiles nothing.
#
#   cmake -DSWAGE_SOURCE_DIR=<checkout> -DSWAGE_IDENTITY_HEADER=<header> \
#     -P cmake/SwageBuildIdentity.cmake
#
# The revision is the full commit hash, followed by `-dirty` when a tracked
# file differs from that commit. It is `unknown` when the sources are not a
# git checkout or git cannot describe them.

set(SWAGE_VERSION_FILE "${SWAGE_SOURCE_DIR}/python/swage/__init__.py")
file(STRINGS "${SWAGE_VERSION_FILE}" SWAGE_VERSION_LINE
  REGEX "^__version__ = \"[^\"]+\"$")
string(REGEX REPLACE "^__version__ = \"([^\"]+)\"$" "\\1"
  SWAGE_BUILD_VERSION "${SWAGE_VERSION_LINE}")
if(NOT SWAGE_BUILD_VERSION)
  message(FATAL_ERROR
    "${SWAGE_VERSION_FILE} has no line of the form __version__ = \"X\", "
    "which names the swage version the bindings are built for.")
endif()

set(SWAGE_BUILD_REVISION "unknown")
find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${SWAGE_SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${SWAGE_SOURCE_DIR}"
    OUTPUT_VARIABLE SWAGE_HEAD
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE SWAGE_HEAD_RESULT)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${SWAGE_SOURCE_DIR}"
    OUTPUT_VARIABLE SWAGE_CHANGES
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE SWAGE_CHANGES_RESULT)
  if(SWAGE_HEAD_RESULT EQUAL 0 AND SWAGE_CHANGES_RESULT EQUAL 0
     AND SWAGE_HEAD MATCHES "^[0-9a-f]+$")
    set(SWAGE_BUILD_REVISION "${SWAGE_HEAD}")
    if(NOT SWAGE_CHANGES STREQUAL "")
      string(APPEND SWAGE_BUILD_REVISION "-dirty")
    endif()
  endif()
endif()

set(SWAGE_IDENTITY_TEXT
"// Generated by cmake/SwageBuildIdentity.cmake on every build. Do not edit.
#ifndef SWAGE_PYTHON_BUILDIDENTITY_H
#define SWAGE_PYTHON_BUILDIDENTITY_H

#define SWAGE_BUILD_VERSION \"${SWAGE_BUILD_VERSION}\"
#define SWAGE_BUILD_REVISION \"${SWAGE_BUILD_REVISION}\"

#endif // SWAGE_PYTHON_BUILDIDENTITY_H
")

set(SWAGE_IDENTITY_PREVIOUS "")
if(EXISTS "${SWAGE_IDENTITY_HEADER}")
  file(READ "${SWAGE_IDENTITY_HEADER}" SWAGE_IDENTITY_PREVIOUS)
endif()
if(NOT SWAGE_IDENTITY_PREVIOUS STREQUAL SWAGE_IDENTITY_TEXT)
  file(WRITE "${SWAGE_IDENTITY_HEADER}" "${SWAGE_IDENTITY_TEXT}")
endif()
