# cmake/SwageBuildIdentity.cmake
# Writes the header that records what a native build was made from: the
# `swage` version in python/swage/__init__.py, the source revision, and the
# digest of the frontend sources beside the bindings.
#
# The build runs this file in script mode before it compiles the Python
# extension, on every build, so the record follows the checkout instead of
# the last configure. The header is rewritten only when its content changes,
# so an unchanged checkout recompiles nothing.
#
#   cmake -DSWAGE_SOURCE_DIR=<checkout> -DSWAGE_IDENTITY_HEADER=<header> \
#     -P cmake/SwageBuildIdentity.cmake
#
# The revision is the full commit hash, followed by `-dirty` when a tracked
# file differs from that commit. It is `unknown` when the sources are not a
# git checkout or git cannot describe them.
#
# The frontend digest is the SHA-256 of one line "<SHA-256 of the file>
# <name>" per Python source under python/swage, in sorted name order, each
# line ending in a newline, where the name is relative to python/swage and
# no part of it starts with a dot. `swage` computes the same digest of the
# package it runs from (`_runtime._frontend_build_digest`) and compares it
# with the one the bindings record.

set(SWAGE_VERSION_FILE "${SWAGE_SOURCE_DIR}/python/swage/__init__.py")
file(STRINGS "${SWAGE_VERSION_FILE}" SWAGE_VERSION_LINE
  REGEX "^__version__ = \"[^\"]+\"$")
string(REGEX REPLACE "^__version__ = \"([^\"]+)\"$" "\\1"
  SWAGE_BUILD_VERSION "${SWAGE_VERSION_LINE}")
if(NOT SWAGE_BUILD_VERSION)
  message(FATAL_ERROR
    "${SWAGE_VERSION_FILE} has no line of the form __version__ = \"X\", "
    "which names the swage version the bindings are built for.")
endif()

set(SWAGE_BUILD_REVISION "unknown")
find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${SWAGE_SOURCE_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
    WORKING_DIRECTORY "${SWAGE_SOURCE_DIR}"
    OUTPUT_VARIABLE SWAGE_HEAD
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE SWAGE_HEAD_RESULT)
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
    WORKING_DIRECTORY "${SWAGE_SOURCE_DIR}"
    OUTPUT_VARIABLE SWAGE_CHANGES
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE SWAGE_CHANGES_RESULT)
  if(SWAGE_HEAD_RESULT EQUAL 0 AND SWAGE_CHANGES_RESULT EQUAL 0
     AND SWAGE_HEAD MATCHES "^[0-9a-f]+$")
    set(SWAGE_BUILD_REVISION "${SWAGE_HEAD}")
    if(NOT SWAGE_CHANGES STREQUAL "")
      string(APPEND SWAGE_BUILD_REVISION "-dirty")
    endif()
  endif()
endif()

set(SWAGE_FRONTEND_DIR "${SWAGE_SOURCE_DIR}/python/swage")
file(GLOB_RECURSE SWAGE_FRONTEND_SOURCES RELATIVE "${SWAGE_FRONTEND_DIR}"
  "${SWAGE_FRONTEND_DIR}/*.py")
list(FILTER SWAGE_FRONTEND_SOURCES EXCLUDE REGEX "(^|/)\\.")
list(SORT SWAGE_FRONTEND_SOURCES)
set(SWAGE_FRONTEND_LINES "")
foreach(SWAGE_FRONTEND_SOURCE IN LISTS SWAGE_FRONTEND_SOURCES)
  # A dangling symbolic link is not a source, as for `swage`.
  if(EXISTS "${SWAGE_FRONTEND_DIR}/${SWAGE_FRONTEND_SOURCE}")
    file(SHA256 "${SWAGE_FRONTEND_DIR}/${SWAGE_FRONTEND_SOURCE}"
      SWAGE_FRONTEND_SOURCE_DIGEST)
    string(APPEND SWAGE_FRONTEND_LINES
      "${SWAGE_FRONTEND_SOURCE_DIGEST}  ${SWAGE_FRONTEND_SOURCE}\n")
  endif()
endforeach()
string(SHA256 SWAGE_BUILD_FRONTEND "${SWAGE_FRONTEND_LINES}")

set(SWAGE_IDENTITY_TEXT
"// Generated by cmake/SwageBuildIdentity.cmake on every build. Do not edit.
#ifndef SWAGE_PYTHON_BUILDIDENTITY_H
#define SWAGE_PYTHON_BUILDIDENTITY_H

#define SWAGE_BUILD_VERSION \"${SWAGE_BUILD_VERSION}\"
#define SWAGE_BUILD_REVISION \"${SWAGE_BUILD_REVISION}\"
#define SWAGE_BUILD_FRONTEND \"${SWAGE_BUILD_FRONTEND}\"

#endif // SWAGE_PYTHON_BUILDIDENTITY_H
")

set(SWAGE_IDENTITY_PREVIOUS "")
if(EXISTS "${SWAGE_IDENTITY_HEADER}")
  file(READ "${SWAGE_IDENTITY_HEADER}" SWAGE_IDENTITY_PREVIOUS)
endif()
if(NOT SWAGE_IDENTITY_PREVIOUS STREQUAL SWAGE_IDENTITY_TEXT)
  file(WRITE "${SWAGE_IDENTITY_HEADER}" "${SWAGE_IDENTITY_TEXT}")
endif()
